version: '2'

services:
  thingsboard:
    image: "thingsboard/application:1.1.0"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683:5683"
    env_file:
      - thingsboard.env
    entrypoint: ./run_thingsboard.sh
  thingsboard-db-schema:
    image: "thingsboard/thingsboard-db-schema:1.1.0"
    env_file:
      - thingsboard-db-schema.env
    entrypoint: ./install_schema.sh
  db:
    image: "cassandra:3.9"
    volumes:
      - "${CASSANDRA_DATA_DIR}:/var/lib/cassandra"
  zk:
    image: "zookeeper:3.4.9"
    restart: always
  kafka_zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: kafka_zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
